//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.15 at 10:31:29 AM CEST 
//


package org.promasi.game.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for projectTaskModel complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="projectTaskModel">
 *   &lt;complexContent>
 *     &lt;extension base="{}model">
 *       &lt;sequence>
 *         &lt;element name="_name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="_description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="_progress" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="_progressEquation" type="{}progressModel" minOccurs="0"/>
 *         &lt;element name="_simulationModel" type="{}simulatorModel" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "projectTaskModel", propOrder = {
    "name",
    "description",
    "progress",
    "progressEquation",
    "simulationModel"
})
public class ProjectTaskModel
    extends Model
{

    @XmlElement(name = "_name")
    protected String name;
    @XmlElement(name = "_description")
    protected String description;
    @XmlElement(name = "_progress")
    protected double progress;
    @XmlElement(name = "_progressEquation")
    protected ProgressModel progressEquation;
    @XmlElement(name = "_simulationModel")
    protected SimulatorModel simulationModel;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the progress property.
     * 
     */
    public double getProgress() {
        return progress;
    }

    /**
     * Sets the value of the progress property.
     * 
     */
    public void setProgress(double value) {
        this.progress = value;
    }

    /**
     * Gets the value of the progressEquation property.
     * 
     * @return
     *     possible object is
     *     {@link ProgressModel }
     *     
     */
    public ProgressModel getProgressEquation() {
        return progressEquation;
    }

    /**
     * Sets the value of the progressEquation property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProgressModel }
     *     
     */
    public void setProgressEquation(ProgressModel value) {
        this.progressEquation = value;
    }

    /**
     * Gets the value of the simulationModel property.
     * 
     * @return
     *     possible object is
     *     {@link SimulatorModel }
     *     
     */
    public SimulatorModel getSimulationModel() {
        return simulationModel;
    }

    /**
     * Sets the value of the simulationModel property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimulatorModel }
     *     
     */
    public void setSimulationModel(SimulatorModel value) {
        this.simulationModel = value;
    }

}
