//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.16 at 01:20:21 PM CET 
//


package org.promasi.utilities.equation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for calculatedEquationModel complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="calculatedEquationModel">
 *   &lt;complexContent>
 *     &lt;extension base="{}equationModel">
 *       &lt;sequence>
 *         &lt;element name="equationString" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "calculatedEquationModel", propOrder = {
    "equationString"
})
public class CalculatedEquationModel
    extends EquationModel
{

    protected String equationString;

    /**
     * Gets the value of the equationString property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEquationString() {
        return equationString;
    }

    /**
     * Sets the value of the equationString property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEquationString(String value) {
        this.equationString = value;
    }

}
