/*
 * Copyright (c) 2006-2011 Rogério Liesenfeld
 * This file is subject to the terms of the MIT license (see LICENSE.txt).
 */
package powermock.examples.mockpolicy.policy;

import mockit.*;
import powermock.examples.mockpolicy.nontest.*;
import powermock.examples.mockpolicy.nontest.domain.*;

/**
 * A mock class that intercepts calls to {@link Dependency#getData()} and returns a substitute
 * value.
 */
@MockClass(realClass = Dependency.class)
public final class MyCustomMockClass
{
   @Mock
   public DataObject getData()
   {
      return new DataObject("Data object generated by mock class");
   }
}
