//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.16 at 01:18:04 PM CET 
//


package org.promasi.sdsystem.model;

import javax.xml.bind.annotation.XmlRegistry;

import org.promasi.utilities.equation.CalculatedEquationModel;
import org.promasi.utilities.equation.EquationModel;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.promasi.sdsystem.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.promasi.sdsystem.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SdSystemModel }
     * 
     */
    public SdSystemModel createSdSystemModel() {
        return new SdSystemModel();
    }

    /**
     * Create an instance of {@link SdSystemModel.SdObjects }
     * 
     */
    public SdSystemModel.SdObjects createSdSystemModelSdObjects() {
        return new SdSystemModel.SdObjects();
    }

    /**
     * Create an instance of {@link OutputSdObjectModel }
     * 
     */
    public OutputSdObjectModel createOutputSdObjectModel() {
        return new OutputSdObjectModel();
    }

    /**
     * Create an instance of {@link Model }
     * 
     */
    public Model createModel() {
        return new Model();
    }

    /**
     * Create an instance of {@link SdSystemBridgeModel }
     * 
     */
    public SdSystemBridgeModel createSdSystemBridgeModel() {
        return new SdSystemBridgeModel();
    }

    /**
     * Create an instance of {@link CalculatedEquationModel }
     * 
     */
    public CalculatedEquationModel createCalculatedEquationModel() {
        return new CalculatedEquationModel();
    }

    /**
     * Create an instance of {@link TimeSdObjectModel }
     * 
     */
    public TimeSdObjectModel createTimeSdObjectModel() {
        return new TimeSdObjectModel();
    }

    /**
     * Create an instance of {@link StockSdObjectModel }
     * 
     */
    public StockSdObjectModel createStockSdObjectModel() {
        return new StockSdObjectModel();
    }

    /**
     * Create an instance of {@link SdObjectModel }
     * 
     */
    public SdObjectModel createSdObjectModel() {
        return new SdObjectModel();
    }

    /**
     * Create an instance of {@link InputSdObjectModel }
     * 
     */
    public InputSdObjectModel createInputSdObjectModel() {
        return new InputSdObjectModel();
    }

    /**
     * Create an instance of {@link FlowSdObjectModel }
     * 
     */
    public FlowSdObjectModel createFlowSdObjectModel() {
        return new FlowSdObjectModel();
    }

    /**
     * Create an instance of {@link EquationModel }
     * 
     */
    public EquationModel createEquationModel() {
        return new EquationModel();
    }

    /**
     * Create an instance of {@link SdSystemModel.SdObjects.Entry }
     * 
     */
    public SdSystemModel.SdObjects.Entry createSdSystemModelSdObjectsEntry() {
        return new SdSystemModel.SdObjects.Entry();
    }

}
