//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.16 at 01:18:04 PM CET 
//


package org.promasi.sdsystem.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

import org.promasi.utilities.equation.EquationModel;


/**
 * <p>Java class for stockSdObjectModel complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="stockSdObjectModel">
 *   &lt;complexContent>
 *     &lt;extension base="{}sdObjectModel">
 *       &lt;sequence>
 *         &lt;element name="equation" type="{}equationModel" minOccurs="0"/>
 *         &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "stockSdObjectModel", propOrder = {
    "equation",
    "value"
})
public class StockSdObjectModel
    extends SdObjectModel
{

    protected EquationModel equation;
    protected Double value;

    /**
     * Gets the value of the equation property.
     * 
     * @return
     *     possible object is
     *     {@link EquationModel }
     *     
     */
    public EquationModel getEquation() {
        return equation;
    }

    /**
     * Sets the value of the equation property.
     * 
     * @param value
     *     allowed object is
     *     {@link EquationModel }
     *     
     */
    public void setEquation(EquationModel value) {
        this.equation = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setValue(Double value) {
        this.value = value;
    }

}
